### ISSUE TITLE
hasura.fetch.upload is not a function 

### ISSUE THREAD

**Issue by kshitij0704** [hasura/js-sdk#17]
The wrapper function hasura.fetch.upload as given in the docs is not defined, such a function does not exists.(url)
![screenshot from 2017-08-07 11-57-59](https://user-images.githubusercontent.com/25777018/29014660-db24756e-7b67-11e7-80dd-4306e8abd452.png)

**Comment by coco98** [comment]
@kshitij0704 Sorry, the README was not updated!
It is just `hasura.fetch(` and not `hasura.fetch.upload(`. Please try again and let us know if it works here.
I've updated the README as well.

**Comment by kshitij0704** [comment]
hasura.fetch( works fine sir, thanks for the quick response
