### ISSUE TITLE
Uncaught (in promise) TypeError: r is not a function

### ISSUE THREAD

**Issue by FlameFractal** [hasura/js-sdk#4]
![image](https://user-images.githubusercontent.com/9962648/28104076-e02b82f8-66f6-11e7-999d-700e3fe613f6.png)

**Comment by coco98** [comment]
@FlameFractal 
1. `onSuccess` and `onError` are functions that you should define.
2. A `}` is missing after the `args` brace is closed.

#### Option 1
Use lambdas or anonymous functions directly for handling success/error.

```javascript
hasura.data.query({
  type: 'select',
  args: {
    table: 'article',
    columns: ['*']
  }},
  (data) => { console.log(data); },
  (error) => { console.log(error); }
);
```

#### Option 2:
Use predefined functions

```javascript
function mySuccessHandler (data) {
  console.log(data);
}

function myErrorHandler (e) {
  console.log(e);
}

hasura.data.query({
  type: 'select',
  args: {
    table: 'article',
    columns: ['*']
  }},
  mySuccessHandler,
  myErrorHandler
);
```

**Comment by jaisontj** [comment]
@coco98 I think the } is missing in the docs as well.

**Comment by coco98** [comment]
@jaisontj  Fixed! 
@FlameFractal  Did this work for you?
