### ISSUE TITLE
Hasura Auth code change

### ISSUE THREAD

**Issue by AjaSharma93** [hasura/js-sdk#8]
The success and error callbacks of the Hasura **Auth** class don't return the corresponding success and error messages with status code. The messages are just printed on the console. The **Data** class on the other hand does return the corresponding messages but no status code.

**Comment by coco98** [comment]
@AjaSharma93 Got it. Can you show us a specific example that you came across? We can fix this asap. Is this happening just for errors?

**Comment by AjaSharma93** [comment]
I'm looking at the source code and can confirm I don't receive the error message in the callback for **hasura.auth.signup(...)**

**Line 41 of Auth.js:**
`onSuccess();`

**Lines 44 and 45 of Auth.js**
`console.log(r);
onError();`

There are similar lines in Data.js for the query functions, for example,

**Lines 21 to 28 of Data.js:**
`(result) => {
        onSuccess(result);
      },
      (e) => {
        logError(e);
        onError(e);
      });`

In the above, you actually send the data and the error message in the callbacks. Why is it different in Auth.js?

Example from my app:
`hasura.setUsername($('#user').val());`
				`hasura.user.email= $("#email").val();`
				`hasura.auth.signup($('#pwd').val(),{}, (success)=>{`
`//redirecting to welcome page`
`}, (err)=>{`
`alert(err); // err doesn't provide a error message`
`});`

**Comment by kshitij0704** [comment]
you can define custom error message , an error in signup will either be due to an issue in code , if query is incorrect else when verification fails if enabled , i dont think signup can give an error if query is correct and verification is successful or is disabled
