### ISSUE TITLE
Correction in Quickstart Documentation

### ISSUE THREAD

**Issue by kshitij0704** [hasura/js-sdk#9]
@coco98 
The example given for quickstart of the readme , the method used is hasura.login("password", onSuccess, onError) whic is not a defined method , it should be hasura.auth.login("password", onSuccess, onError) in the docs 
![screenshot from 2017-07-24 11-11-00](https://user-images.githubusercontent.com/25777018/28509679-6c70bdaa-7061-11e7-9677-f44903bb2c01.png)
![screenshot from 2017-07-24 11-17-28](https://user-images.githubusercontent.com/25777018/28509736-b61c9bf4-7061-11e7-9419-a696d4b76311.png)

**Comment by AbhishekBhattacharya** [comment]
@kshitij0704  already submited a PR for for it , ```hasura.auth.login``` works. It is mentioned in **Auth.js** also.
I guess only we both are using js sdk :)
